[workspace]
resolver = "3"
members = ["crates/khem", "crates/khem-core"]

[workspace.package]
version = "0.0.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/funkybooboo/khem"

[workspace.dependencies]
khem-core = { path = "crates/khem-core" }

[workspace.lints.rust]
unsafe_code = "forbid"